backend:
  name: github
  repo: fernandoaris-coder/Cheeseboardsandthangs.2
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "carousel"
    label: "Home Page Carousel"
    folder: "content/carousel"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
